@startuml Features

actor :Chuyên viên: as cv
actor :Chủ cơ sỏ: as ccs
actor :Người quản lý: as ngl

rectangle "Tra cứu thông tin về cơ sở" {
    usecase "Tra cứu giấy chứng nhận" as ccs_UC1
    usecase "Tra cứu kết quả kiểm tra" as ccs_UC3
    usecase "Yêu cầu cấp giấy chứng nhận" as ccs_UC2
    usecase "In giấy chứng nhận" as ccs_UC4

}
ccs --> ccs_UC1
ccs --> ccs_UC2
ccs --> ccs_UC3
ccs --> ccs_UC4

rectangle "Quản lý giấy chứng nhận cơ sở" {
    usecase "Cấp giấy chứng nhận" as cv_UC1
    usecase "Thu hồi giấy chứng nhận" as cv_UC2
    usecase "In giấy chứng nhận" as cv_UC3
}

rectangle "Quản lý kết quả thanh kiểm tra" {
    usecase "Tạo kế hoạch kiểm tra" as cv_UC4
}

rectangle "Quản lý cơ sở kinh doanh" {
    usecase "Thêm cơ sở" as cv_UC5
    usecase "Xóa cơ sở" as cv_UC6
    usecase "Điều chỉnh thông tin cơ sở" as cv_UC7
}

rectangle "Quản lý mẫu thực phẩm" {
    usecase "Tra cứu kết quả mẫu" as cv_UC8
    usecase "Điều chỉnh kết quả mẫu" as cv_UC9
    usecase "Xóa kết quả mẫu" as cv_UC10
}
cv --> cv_UC1
cv --> cv_UC2
cv --> cv_UC3
cv --> cv_UC4
cv --> cv_UC6
cv --> cv_UC7
cv --> cv_UC8
cv --> cv_UC9
cv --> cv_UC10

rectangle "Quản lý người dùng" {
    usecase "Phân quyền tài khoản" as ngl_UC1
    usecase "Thêm người dùng" as ngl_UC2
    usecase "Điều chỉnh thông tin người dùng" as ngl_UC3
}

ngl --> cv_UC1
ngl --> cv_UC2
ngl --> cv_UC3
ngl --> cv_UC4
ngl --> cv_UC4
ngl --> ngl_UC1
ngl --> ngl_UC2
ngl --> ngl_UC3

@enduml