export enum ActionTypes {
  APP__CHANGE_MENU_STATE = 0x00,
  APP__OPEN_DIALOG = 0x01,
  APP__CHANGE_SHOW_REGIS_FORM_STATE = 0x02,
  APP__REMOVE_NOTIFICATION = 0x03,
  APP__NOTIFY = 0x04,

  ACCOUNT_TABLE__SET_ITEMS_COUNT = 0x10,
  ACCOUNT_TABLE__SET_PAGE = 0x11,
  ACCOUNT_TABLE__SET_RPP = 0x12,

  ACCOUNT_DATA__SET_DATA = 0x20,
}
